# In this directory, run the following command to build this builder.
# $ gcloud builds submit

steps:

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    set -e  # Fail if any command below fails
    docker build \
    --tag=us-docker.pkg.dev/$PROJECT_ID/docker/covid-data-model:${SHORT_SHA} \
    --tag=us-docker.pkg.dev/$PROJECT_ID/docker/covid-data-model:latest .

images:
  - 'us-docker.pkg.dev/$PROJECT_ID/docker/covid-data-model:$SHORT_SHA'
  - 'us-docker.pkg.dev/$PROJECT_ID/docker/covid-data-model:latest'
