#!/bin/bash

git clone https://github.com/covid-projections/covid-data-public.git
cd covid-data-public
git lfs pull
ls -lh data/cases-cds
cd ../

pip install -e covid-data-public
export COVID_DATA_PUBLIC=covid-data-public
