name: MyBinder

on:
  pull_request:

jobs:
  mybinder-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: s-weigand/trigger-mybinder-build@v1
        with:
          target-repo: covid-projections/covid-data-model
          target-state: ${{ github.head_ref }}
