name: Test Python Setup on GCE Runner

on: [push]

jobs:
  build:
    runs-on: [self-hosted, gce-runner]
    strategy:
      matrix:
        python-version: '3.x'
    name: Python ${{ matrix.python-version }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: python my_script.py